# Generated by Django 4.2.3 on 2023-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_motiondetection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motiondetection",
            name="classroom",
        ),
        migrations.AddField(
            model_name="motiondetection",
            name="clname",
            field=models.CharField(default=1.3, max_length=100),
            preserve_default=False,
        ),
    ]
